[package]
name = "davSync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ical = "0.7.0"
tokio = { version = "1", features = ["full"] }
reqwest = { version = " 0.11.10"}
error-chain = "0.12.4"